//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace vize2.Database4
{

    public partial class AMBAR : XPLiteObject
    {
        string fadres;
        [Size(SizeAttribute.Unlimited)]
        public string adres
        {
            get { return fadres; }
            set { SetPropertyValue<string>(nameof(adres), ref fadres, value); }
        }
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        int fkapasite;
        [ColumnDbDefaultValue("0")]
        public int kapasite
        {
            get { return fkapasite; }
            set { SetPropertyValue<int>(nameof(kapasite), ref fkapasite, value); }
        }
        KULLANICIPANELI fyetkili;
        [Size(255)]
        [Association(@"AMBARReferencesKULLANICIPANELI")]
        public KULLANICIPANELI yetkili
        {
            get { return fyetkili; }
            set { SetPropertyValue<KULLANICIPANELI>(nameof(yetkili), ref fyetkili, value); }
        }
    }

}
