//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace vize2.Database4
{

    public partial class GirenCIKAN : XPLiteObject
    {
        string falici;
        [Size(255)]
        public string alici
        {
            get { return falici; }
            set { SetPropertyValue<string>(nameof(alici), ref falici, value); }
        }
        string fgonderen;
        [Size(255)]
        public string gonderen
        {
            get { return fgonderen; }
            set { SetPropertyValue<string>(nameof(gonderen), ref fgonderen, value); }
        }
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fislemtipi;
        [Size(255)]
        public string islemtipi
        {
            get { return fislemtipi; }
            set { SetPropertyValue<string>(nameof(islemtipi), ref fislemtipi, value); }
        }
        DateTime ftarih;
        public DateTime tarih
        {
            get { return ftarih; }
            set { SetPropertyValue<DateTime>(nameof(tarih), ref ftarih, value); }
        }
        string ftopdeger;
        [Size(255)]
        public string topdeger
        {
            get { return ftopdeger; }
            set { SetPropertyValue<string>(nameof(topdeger), ref ftopdeger, value); }
        }
        string ftopmiktar;
        [Size(255)]
        public string topmiktar
        {
            get { return ftopmiktar; }
            set { SetPropertyValue<string>(nameof(topmiktar), ref ftopmiktar, value); }
        }
        string fURUN_ad;
        [Indexed(Name = @"GirenCIKANURUN_ad")]
        [Size(255)]
        public string URUN_ad
        {
            get { return fURUN_ad; }
            set { SetPropertyValue<string>(nameof(URUN_ad), ref fURUN_ad, value); }
        }
    }

}
