//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace vize2.Database4
{

    public partial class STOK : XPLiteObject
    {
        string falıcıfirma;
        [Size(255)]
        public string alıcıfirma
        {
            get { return falıcıfirma; }
            set { SetPropertyValue<string>(nameof(alıcıfirma), ref falıcıfirma, value); }
        }
        int fdeğeri;
        [ColumnDbDefaultValue("0")]
        public int değeri
        {
            get { return fdeğeri; }
            set { SetPropertyValue<int>(nameof(değeri), ref fdeğeri, value); }
        }
        string fgönderenfirma;
        [Size(255)]
        public string gönderenfirma
        {
            get { return fgönderenfirma; }
            set { SetPropertyValue<string>(nameof(gönderenfirma), ref fgönderenfirma, value); }
        }
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        int fmiktar;
        [ColumnDbDefaultValue("0")]
        public int miktar
        {
            get { return fmiktar; }
            set { SetPropertyValue<int>(nameof(miktar), ref fmiktar, value); }
        }
        DateTime fsaklamasüresi;
        public DateTime saklamasüresi
        {
            get { return fsaklamasüresi; }
            set { SetPropertyValue<DateTime>(nameof(saklamasüresi), ref fsaklamasüresi, value); }
        }
        URUN fURUN_ad;
        [Size(255)]
        [Association(@"STOKReferencesURUN")]
        public URUN URUN_ad
        {
            get { return fURUN_ad; }
            set { SetPropertyValue<URUN>(nameof(URUN_ad), ref fURUN_ad, value); }
        }
    }

}
